version: '3.3'
services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

# services running on kubernetes
  # wp:
  #   container_name: wp
  #   image: ghcr.io/onvrb/sd-tp2-wordpress:master
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./wp:/config
  #   restart: unless-stopped
  #   depends_on:
  #     - mariadb

  # mariadb:
  #   container_name: mariadb
  #   image: ghcr.io/onvrb/sd-tp2-mariadb:main
  #   # ports:
  #     # - "3306:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=safe_root_password
  #     - MYSQL_DATABASE=wordpress
  #     - MYSQL_USER=wordpress
  #     - MYSQL_PASSWORD=wordpress
  #   volumes:
  #     - ./mariadb:/var/lib/mysql
  #   restart: unless-stopped
